spring.application.name=Resort_uz
server.port=${PORT:8080}
server.servlet.context-path=/api

# Render PostgreSQL ? to'g'ridan URL
spring.datasource.url=jdbc:postgresql://${PGHOST}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB

app.upload.dir=/app/uploads
app.upload.allowed-extensions=jpg,jpeg,png,webp

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

app.jwt.secret=${JWT_SECRET:scKjxMbna5BWcovn1PQ6wC7fEzq7PqsAxxQJl4sN3Tq}
app.jwt.expiration=86400000

app.telegram.bot-token=${TELEGRAM_BOT_TOKEN:}
app.telegram.admin-chat-id=${TELEGRAM_ADMIN_CHAT_ID:}

imgbb.api.key=${IMGBB_API_KEY:b652b80a8cb92deadba86915dae9d7ec}