spring.application.name=Resort_uz

server.port=${PORT:8080}
server.servlet.context-path=/api

# Railway PostgreSQL ? env variables dan olinadi
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB

# Production da uploads papkasi
app.upload.dir=/app/uploads
app.upload.allowed-extensions=jpg,jpeg,png,webp

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.config-url=/api/v3/api-docs/swagger-config
springdoc.swagger-ui.url=/api/v3/api-docs
springdoc.swagger-ui.disable-swagger-default-url=true

app.jwt.secret=${JWT_SECRET:scKjxMbna5BWcovn1PQ6wC7fEzq7PqsAxxQJl4sN3Tq}
app.jwt.expiration=86400000

app.telegram.bot-token=${TELEGRAM_BOT_TOKEN:}
app.telegram.admin-chat-id=${TELEGRAM_ADMIN_CHAT_ID:}
