spring.application.name=Resort_uz
app.base-url=http://localhost:8080/api

#  SERVER
# ================================================
server.port=8080
server.servlet.context-path=/api

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
# ============================================

# ================================================
#  FAYL YUKLASH (rasm upload)
# ================================================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB

# Upload papka yo'li (profillarda o'zgaradi)
app.upload.dir=C:/Users/DIOR/IdeaProjects/Resort_uz/uploads
app.upload.allowed-extensions=jpg,jpeg,png,webp

# ================================================
#  SWAGGER / OPENAPI
# ================================================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.config-url=/api/v3/api-docs/swagger-config
springdoc.swagger-ui.url=/api/v3/api-docs
springdoc.swagger-ui.disable-swagger-default-url=true

# ================================================
#  JPA UMUMIY
# ================================================
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

app.eskiz.email=davlatbeksultonov1406@gmail.com
app.eskiz.password=R8S6gnvTDa8zgM@
app.eskiz.sender=4546
app.jwt.secret=scKjxMbna5BWcovn1PQ6wC7fEzq7PqsAxxQJl4sN3Tq
app.jwt.expiration=86400000